### ISSUE TITLE
Karma & ZenjectSceneLoader

### ISSUE THREAD

**Issue by quinkennedy** [cgarciae/karma#7]
I have a scene that I want to load, and ideally share context with. It seems like ZenjectSceneLoader is an appropriate way to load in the new scene, but It doesn't seem like Karma's organization allows for that.

If I include:
```
[Inject]
public void PostConstructor(ZenjectSceneLoader sceneLoader)...
```
then I receive the following error: 
```
Zenject.ZenjectException: Unable to resolve type 'ZenjectSceneLoader' while building object... 
```

If I also include the following in `Startup.Configure`: 
```
container.Bind<ZenjectSceneLoader> ().FromResolve ().AsSingle ();
```
then I receive the following error instead:
```
Zenject.ZenjectException: Assert hit! Found circular dependency when creating type 'Zenject.ZenjectSceneLoader'
```

ZenjectSceneLoader depends on a SceneContext, which as far as I can tell is not created. It seems that neither SceneContext nor ProjectContext are created when using Karma. Is the intention to only use vanilla Dependency Injection from Zenject without bothering with a lot of the extra features of Zenject?

**Comment by SacredSkull** [comment]
Support was added for existing contexts as of 921d5cdd0512e8693174706b70cd41f1343ec7a6 - for anyone else, tick the *Use Zenject Contexts* on your App object.
